repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types:
          - "text"
          - "markdown"
          - "svg"
        exclude: "android/.*|ios/.*"
      - id: trailing-whitespace
        exclude: "android/.*|ios/.*"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: "android/.*|ios/.*"
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
